# This is a basic workflow to help you get started with Actions

name: RequiredApprovals

# Controls when the workflow will run
on:
  - pull_request_review
  - pull_request

jobs:
  get-reviewers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make REST API request
      run: |
        response=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ github.event.number }}/requested_reviewers)
        echo "$response" | jq -r '.teams.[] | .slug'
